spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yidiandian.entity
server:
  port: 8080

logging:
  level:
    com.yidiandian.dao: debug

